Feat: updating logging channel
Signed-off-by: Aniket Gohel <123355145+aniketgohelimp@users.noreply.github.com>

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/proxysql/run b/rootfs/etc/s6-overlay/s6-rc.d/proxysql/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/proxysql/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/proxysql/run
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
 if [ -n "$CONFILEFILE" ]; then
-    proxysql -f --idle-threads -D /var/lib/proxysql -c $CONFILEFILE
+    proxysql -f --idle-threads -D /var/lib/proxysql -c $CONFILEFILE 1>/dev/stdout 2>&1 |while IFS= read -r line; do echo "$line" | grep -q 'ERROR' && echo "$line" >&2 || echo "$line"; done
 fi
-proxysql -f --idle-threads -D /var/lib/proxysql
+proxysql -f --idle-threads -D /var/lib/proxysql 1>/dev/stdout 2>&1 |while IFS= read -r line; do echo "$line" | grep -q 'ERROR' && echo "$line" >&2 || echo "$line"; done
